services:
  - type: web
    name: my-free-web-app
    env: node
    plan: free                  # <-- IMPORTANT
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
