services:
  - type: web
    name: my-web-app
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    region: oregon

databases:
  - name: my-db
    plan: starter
  
